### ISSUE TITLE
error while running train_second.py (caused by size mismatch)

### ISSUE THREAD

**Issue by exllama-fan** [yl4579/StyleTTS#41]
Traceback (most recent call last):
  File "/home/jumpcloud/libraries/StyleTTS/train_second.py", line 494, in <module>
    main()
  File "/home/jumpcloud/miniconda3/envs/work/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/jumpcloud/miniconda3/envs/work/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/jumpcloud/miniconda3/envs/work/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jumpcloud/miniconda3/envs/work/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/jumpcloud/libraries/StyleTTS/train_second.py", line 220, in main
    bert_dur = model.bert(texts, attention_mask=(~text_mask).int()).last_hidden_state
  File "/home/jumpcloud/miniconda3/envs/work/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jumpcloud/miniconda3/envs/work/lib/python3.10/site-packages/transformers/models/albert/modeling_albert.py", line 724, in forward
    buffered_token_type_ids_expanded = buffered_token_type_ids.expand(batch_size, seq_length)
RuntimeError: The expanded size of the tensor (584) must match the existing size (512) at non-singleton dimension 1.  Target sizes: [12, 584].  Tensor sizes: [1, 512]

**Comment by yl4579** [comment]
Is it a problem in PL-BERT or StyleTTS?

**Comment by exllama-fan** [comment]
problem is with PL-BERT based styleTTS and the cause of that is if there's any transcription longer than 512 character length, it will throw an error, so fixed my dataset creator accordingly, it works now
